-- TEST-ONLY. Lives in src/test/resources, so Flyway sees it in tests and
-- never in a deployed service. V900 keeps it far above any real migration.
--
-- The table exists so the tenant discriminator can be proved before the first
-- domain table arrives (T-1.2 brings those, each with tenant_id NOT NULL from
-- its first migration). The shape here is the shape every tenant-scoped table
-- will have, NOT NULL included -- a nullable tenant column produces rows that
-- match no filter and are invisible to the tenant that owns them.

CREATE TABLE tenancy_probe (
    id        bigint       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id varchar(64)  NOT NULL,
    note      varchar(255)
);
