package com.xenopsoftware.learn.catalog.web.rest;

import com.xenopsoftware.learn.catalog.gate.Combinator;
import com.xenopsoftware.learn.catalog.gate.GateRule;
import com.xenopsoftware.learn.catalog.gate.GateService;
import com.xenopsoftware.learn.catalog.gate.Reachability;
import com.xenopsoftware.learn.catalog.gate.RequiredState;
import com.xenopsoftware.learn.catalog.gate.StructurePart;
import java.util.List;
import java.util.Locale;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

/**
 * Gates, and what a learner may reach (T-5.3).
 *
 * <p><b>The client is told what is reachable and why; it is never asked.</b> There is no endpoint
 * here that accepts a client's opinion about whether something is unlocked — reachability is
 * computed server-side from gates the server holds and completions the server recorded, and the
 * response carries the sentence to display so a screen never has to derive one. A UI that composed
 * its own explanation from the requirement list would be a second implementation of the rule, and
 * the day it disagreed a learner would be told they may proceed while the server refuses.
 */
@RestController
@RequestMapping("/api/v1/courses")
public class GateResource {

    private final GateService gates;

    public GateResource(GateService gates) {
        this.gates = gates;
    }

    /**
     * @param combinator ALL or ANY, and there is deliberately no third option and no expression
     *                   string: a rule that can only be evaluated by parsing is a rule that cannot
     *                   be explained without a second parser
     */
    public record GateRequest(String combinator, List<RequirementRequest> requirements) {}

    public record RequirementRequest(String part, UUID id, String state) {}

    public record RequirementView(String part, UUID id, String state) {}

    public record GateView(String targetPart, UUID targetId, String combinator,
                           List<RequirementView> requirements) {}

    /**
     * @param explanation the sentence to show, generated by the same walk that decided
     *                    {@code reachable} — display it rather than composing one
     * @param unmet       the same requirements as a list, for a checklist UI that wants them
     *                    itemised. Never a substitute for the sentence.
     */
    public record ReachabilityView(String part, UUID id, boolean reachable, String explanation,
                                   List<UnmetView> unmet) {}

    public record UnmetView(String part, UUID id, String title, String state, String phrase) {}

    /** Puts a gate on a module or a node, replacing whatever rule was there. */
    @PutMapping("/{courseId}/gates/{targetPart}/{targetId}")
    public GateView save(@PathVariable UUID courseId, @PathVariable String targetPart,
            @PathVariable UUID targetId, @RequestBody GateRequest request) {
        List<GateService.RequirementSpec> specs = request.requirements() == null ? List.of()
            : request.requirements().stream()
                .map(requirement -> new GateService.RequirementSpec(part(requirement.part()),
                    requirement.id(), state(requirement.state())))
                .toList();
        return view(gates.save(courseId, part(targetPart), targetId,
            combinator(request.combinator()), specs));
    }

    @DeleteMapping("/{courseId}/gates/{targetPart}/{targetId}")
    public void remove(@PathVariable UUID courseId, @PathVariable String targetPart,
            @PathVariable UUID targetId) {
        gates.remove(targetId);
    }

    /** The rule on one target, for the authoring screen that edits it. */
    @GetMapping("/{courseId}/gates/{targetPart}/{targetId}")
    public GateView rule(@PathVariable UUID courseId, @PathVariable String targetPart,
            @PathVariable UUID targetId) {
        return gates.ruleOn(targetId).map(GateResource::view)
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "No gate there"));
    }

    /**
     * What this learner may reach, and why not where they may not.
     *
     * @param learnerId whose reachability to compute. Taken as a parameter rather than from the
     *                  token because an author previewing a course as a particular learner is a
     *                  real need — and because the answer is not a secret from the person who can
     *                  already read the whole course. Once grants travel between services
     *                  (T-9.11), reading somebody else's should require a permission; that gap is
     *                  recorded in {@code CatalogCoverageTest} with the rest.
     */
    @GetMapping("/{courseId}/reachability")
    public List<ReachabilityView> reachability(@PathVariable UUID courseId,
            @RequestParam UUID learnerId) {
        return gates.reachability(courseId, learnerId).stream().map(GateResource::view).toList();
    }

    private static ReachabilityView view(Reachability answer) {
        return new ReachabilityView(answer.part().name(), answer.id(), answer.reachable(),
            answer.explanation(), answer.unmet().stream()
                .map(unmet -> new UnmetView(unmet.part().name(), unmet.id(), unmet.title(),
                    unmet.state().name(), unmet.phrase()))
                .toList());
    }

    private static GateView view(GateRule rule) {
        return new GateView(rule.targetPart().name(), rule.targetId(), rule.combinator().name(),
            rule.requirements().stream()
                .map(requirement -> new RequirementView(requirement.part().name(),
                    requirement.id(), requirement.state().name()))
                .toList());
    }

    private static StructurePart part(String value) {
        return parse(StructurePart.class, value, "part must be MODULE or NODE");
    }

    private static RequiredState state(String value) {
        return parse(RequiredState.class, value, "state must be COMPLETED or PASSED");
    }

    private static Combinator combinator(String value) {
        return parse(Combinator.class, value, "combinator must be ALL or ANY");
    }

    private static <E extends Enum<E>> E parse(Class<E> type, String value, String complaint) {
        try {
            return Enum.valueOf(type, value == null ? "" : value.toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, complaint);
        }
    }
}
