-- V1 — the baseline.
--
-- Deliberately almost empty. It exists so the migration history starts at a
-- known point and Flyway has something to record, rather than the first real
-- migration being the baseline by accident.
--
-- No domain tables yet: app_user, tenant, group and the permission tables are
-- T-1.2, T-1.3 and T-2.1, and each one arrives with its own migration written
-- before the entity.

CREATE TABLE schema_marker (
    id         integer     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    module     varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Which module owns this database. Reads as trivia until someone is looking at
-- a connection in pg_stat_activity and cannot tell which service opened it.
INSERT INTO schema_marker (module) VALUES ('identity');
