-- V1 — the baseline. Same shape and same reasoning as identity's: the history
-- starts at a known point, and the marker answers "which module owns this
-- database" from pg_stat_activity.

CREATE TABLE schema_marker (
    id         integer     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    module     varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO schema_marker (module) VALUES ('streaming');
