-- V1 — the baseline. Same shape and reasoning as identity's and streaming's:
-- the migration history starts at a known point, and the marker answers "which
-- module owns this database" from pg_stat_activity.
--
-- Nothing else yet, deliberately. Telemetry ingest is T-7.1, the day partitions
-- are T-7.2 and the rollups are T-7.3; each arrives with its own migration
-- written before the code that reads it. What this issue establishes is that
-- the database exists, that it is reporting's alone, and that nothing in a
-- learner's request path calls into the service that owns it.

CREATE TABLE schema_marker (
    id         integer     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    module     varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO schema_marker (module) VALUES ('reporting');
